src/main/java/com/andaily/hb/domain/dto/log/FrequencyMonitorLogDto.java
package com.andaily.hb.domain.dto.log;

import com.andaily.hb.domain.application.ApplicationInstance;
import com.andaily.hb.domain.dto.AbstractDto;
import com.andaily.hb.domain.log.FrequencyMonitorLog;
import com.andaily.hb.infrastructure.DateUtils;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * 15-2-13
 *
 * @author Shengzhao Li
 */
public class FrequencyMonitorLogDto extends AbstractDto {

    private static final BigDecimal KB = new BigDecimal("1024");

    private String instanceGuid;
    private String instanceName;

    private boolean normal;
    private String createTime;
    private String createDate;

    private long costTime;
    private String remark;

    private long responseSize;

    public FrequencyMonitorLogDto() {
    }

    public FrequencyMonitorLogDto(FrequencyMonitorLog log) {
        super(log.guid());
        final Date time = log.createTime();
        this.createTime = DateUtils.toDateText(time, DateUtils.DEFAULT_DATE_TIME_FORMAT);
        this.createDate = DateUtils.toDateText(time);

        ApplicationInstance instance = log.instance();
        this.instanceGuid = instance.guid();
        this.instanceName = instance.instanceName();

        this.normal = log.normal();
        this.costTime = log.costTime();
        this.remark = log.remark();

        this.responseSize = log.responseSize();
    }

    public String getCreateDate() {
        return createDate;
    }

    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    public String getCreateTime() {
        return createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    public String getInstanceGuid() {
        return instanceGuid;
    }

    public void setInstanceGuid(String instanceGuid) {
        this.instanceGuid = instanceGuid;
    }

    public String getInstanceName() {
        return instanceName;
    }

    public void setInstanceName(String instanceName) {
        this.instanceName = instanceName;
    }

    public boolean isNormal() {
        return normal;
    }

    public void setNormal(boolean normal) {
        this.normal = normal;
    }

    public long getCostTime() {
        return costTime;
    }

    public void setCostTime(long costTime) {
        this.costTime = costTime;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public long getResponseSize() {
        return responseSize;
    }

    public BigDecimal getResponseSizeAsKB() {
        return new BigDecimal(responseSize).divide(KB, 2, BigDecimal.ROUND_HALF_UP);
    }

    public void setResponseSize(long responseSize) {
        this.responseSize = responseSize;
    }

    public static List<FrequencyMonitorLogDto> toDtos(List<FrequencyMonitorLog> logs) {
        List<FrequencyMonitorLogDto> dtos = new ArrayList<>(logs.size());
        for (FrequencyMonitorLog log : logs) {
            dtos.add(new FrequencyMonitorLogDto(log));
        }
        return dtos;
    }
}

src/main/java/com/andaily/hb/domain/dto/log/FrequencyMonitorLogListDto.java
package com.andaily.hb.domain.dto.log;

import com.andaily.hb.domain.dto.application.ApplicationInstanceDto;
import com.andaily.hb.domain.shared.paginated.DefaultPaginated;
import com.andaily.hb.infrastructure.grouper.GroupResult;
import com.andaily.hb.infrastructure.grouper.impl.FrequencyMonitorLogDtoCreateTimeGrouper;
import org.apache.commons.lang.StringUtils;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/**
 * 15-2-13
 *
 * @author Shengzhao Li
 */
public class FrequencyMonitorLogListDto extends DefaultPaginated<FrequencyMonitorLogDto> {


    private String instanceGuid;
    //1 is normal,2 is not normal, otherwise all
    private int normal = 0;
    private OrderItem orderItem = OrderItem.LOG_TIME;


    private int cleanMonitorLogFrequency;

    private List<ApplicationInstanceDto> instanceDtos = new ArrayList<>();

    public FrequencyMonitorLogListDto() {
    }

    @Override
    public Map<String, Object> queryMap() {
        Map<String, Object> map = super.queryMap();
        map.put("instanceGuid", instanceGuid);
        map.put("normal", normal);
        map.put("orderItem", orderItem.getField());
        return map;
    }


    public List<GroupResult<String, FrequencyMonitorLogDto>> getListGroupResults() {
        FrequencyMonitorLogDtoCreateTimeGrouper grouper = new FrequencyMonitorLogDtoCreateTimeGrouper(list);
        return grouper.group().getGroupResults();
    }

    public OrderItem[] getOrderItems() {
        return OrderItem.values();
    }

    public ApplicationInstanceDto getInstanceDto() {
        if (StringUtils.isNotEmpty(instanceGuid)) {
            for (ApplicationInstanceDto instanceDto : instanceDtos) {
                if (instanceDto.getGuid().equals(instanceGuid)) {
                    return instanceDto;
                }
            }
        }
        return null;
    }

    public OrderItem getOrderItem() {
        return orderItem;
    }

    public void setOrderItem(OrderItem orderItem) {
        this.orderItem = orderItem;
    }

    public List<ApplicationInstanceDto> getInstanceDtos() {
        return instanceDtos;
    }

    public int getNormal() {
        return normal;
    }

    public void setNormal(int normal) {
        this.normal = normal;
    }

    public String getInstanceGuid() {
        return instanceGuid;
    }

    public void setInstanceGuid(String instanceGuid) {
        this.instanceGuid = instanceGuid;
    }

    public int getCleanMonitorLogFrequency() {
        return cleanMonitorLogFrequency;
    }

    public void setCleanMonitorLogFrequency(int cleanMonitorLogFrequency) {
        this.cleanMonitorLogFrequency = cleanMonitorLogFrequency;
    }


    /**
     * Order item
     */
    public static enum OrderItem {
        LOG_TIME("createTime", "日志时间"),
        CONN_TIME("costTime", "连接用时");
        private String field;
        private String label;

        private OrderItem(String field, String label) {
            this.field = field;
            this.label = label;
        }

        public String getLabel() {
            return label;
        }

        public String getField() {
            return field;
        }

        public String getValue() {
            return name();
        }
    }

}

src/main/java/com/andaily/hb/domain/dto/log/MonitoringReminderLogDto.java
package com.andaily.hb.domain.dto.log;

import com.andaily.hb.domain.application.ApplicationInstance;
import com.andaily.hb.domain.dto.AbstractDto;
import com.andaily.hb.domain.log.MonitoringReminderLog;
import com.andaily.hb.infrastructure.DateUtils;

import java.util.ArrayList;
import java.util.List;

/**
 * 15-3-14
 *
 * @author Shengzhao Li
 */
public class MonitoringReminderLogDto extends AbstractDto {


    private static final long serialVersionUID = -5847847178614825293L;
    private String createTime;

    private FrequencyMonitorLogDto monitorLogDto;

    private String instanceGuid;
    private String instanceName;

    private boolean changeNormal;

    private String receiveEmail;

    private String emailContent;

    private String openId;

    //微信的内容
    private String weChartContent;


    public MonitoringReminderLogDto() {
    }

    public MonitoringReminderLogDto(MonitoringReminderLog log) {
        super(log.guid());
        this.createTime = DateUtils.toDateTime(log.createTime());
        this.monitorLogDto = new FrequencyMonitorLogDto(log.monitorLog());

        final ApplicationInstance instance = log.instance();
        this.instanceGuid = instance.guid();
        this.instanceName = instance.instanceName();

        this.changeNormal = log.changeNormal();
        this.emailContent = log.emailContent();
        this.receiveEmail = log.receiveEmail();

        this.openId = log.openId();
        this.weChartContent = log.weChartContent();
    }

    public String getOpenId() {
        return openId;
    }

    public void setOpenId(String openId) {
        this.openId = openId;
    }

    public String getWeChartContent() {
        return weChartContent;
    }

    public void setWeChartContent(String weChartContent) {
        this.weChartContent = weChartContent;
    }

    public String getCreateTime() {
        return createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    public FrequencyMonitorLogDto getMonitorLogDto() {
        return monitorLogDto;
    }

    public void setMonitorLogDto(FrequencyMonitorLogDto monitorLogDto) {
        this.monitorLogDto = monitorLogDto;
    }

    public String getInstanceGuid() {
        return instanceGuid;
    }

    public void setInstanceGuid(String instanceGuid) {
        this.instanceGuid = instanceGuid;
    }

    public String getInstanceName() {
        return instanceName;
    }

    public void setInstanceName(String instanceName) {
        this.instanceName = instanceName;
    }

    public boolean isChangeNormal() {
        return changeNormal;
    }

    public void setChangeNormal(boolean changeNormal) {
        this.changeNormal = changeNormal;
    }

    public String getReceiveEmail() {
        return receiveEmail;
    }

    public void setReceiveEmail(String receiveEmail) {
        this.receiveEmail = receiveEmail;
    }

    public String getEmailContent() {
        return emailContent;
    }

    public void setEmailContent(String emailContent) {
        this.emailContent = emailContent;
    }

    public static List<MonitoringReminderLogDto> toDtosa(List<MonitoringReminderLog> logs) {
        List<MonitoringReminderLogDto> dtos = new ArrayList<>(logs.size());
        for (MonitoringReminderLog log : logs) {
            dtos.add(new MonitoringReminderLogDto(log));
        }
        return dtos;
    }
}

src/main/java/com/andaily/hb/domain/dto/log/ReminderLogListDto.java
package com.andaily.hb.domain.dto.log;

import com.andaily.hb.domain.dto.application.ApplicationInstanceDto;
import com.andaily.hb.domain.shared.paginated.DefaultPaginated;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/**
 * 15-3-14
 *
 * @author Shengzhao Li
 */
public class ReminderLogListDto extends DefaultPaginated<MonitoringReminderLogDto> {


    private String instanceGuid;
    //1 is un-normal -> normal,0 is normal -> un-normal , otherwise all
    private int normal = -1;



    private int cleanMonitorLogFrequency;


    private ApplicationInstanceDto instanceDto;
    private List<ApplicationInstanceDto> instanceDtos = new ArrayList<>();


    public ReminderLogListDto() {
    }


    @Override
    public Map<String, Object> queryMap() {
        final Map<String, Object> map = super.queryMap();
        map.put("instanceGuid", instanceGuid);
        map.put("normal", normal);
        return map;
    }

    public ApplicationInstanceDto getInstanceDto() {
        return instanceDto;
    }

    public void setInstanceDto(ApplicationInstanceDto instanceDto) {
        this.instanceDto = instanceDto;
    }

    public String getInstanceGuid() {
        return instanceGuid;
    }

    public void setInstanceGuid(String instanceGuid) {
        this.instanceGuid = instanceGuid;
    }

    public int getNormal() {
        return normal;
    }

    public void setNormal(int normal) {
        this.normal = normal;
    }

    public List<ApplicationInstanceDto> getInstanceDtos() {
        return instanceDtos;
    }

    public void setInstanceDtos(List<ApplicationInstanceDto> instanceDtos) {
        this.instanceDtos = instanceDtos;
    }

    public int getCleanMonitorLogFrequency() {
        return cleanMonitorLogFrequency;
    }

    public void setCleanMonitorLogFrequency(int cleanMonitorLogFrequency) {
        this.cleanMonitorLogFrequency = cleanMonitorLogFrequency;
    }
}

src/main/java/com/andaily/hb/domain/log/FrequencyMonitorLog.java
package com.andaily.hb.domain.log;

import com.andaily.hb.domain.AbstractDomain;
import com.andaily.hb.domain.application.ApplicationInstance;

import javax.persistence.*;
import java.util.Date;

/**
 * 14-11-23
 * 实例每一次监控的 日志
 * 这是由定时任务每一次执行后的结果
 *
 * @author Shengzhao Li
 */
@Entity
@Table(name = "frequency_monitor_log")
public class FrequencyMonitorLog extends AbstractDomain {

    private static final long serialVersionUID = 4517860393571033878L;
    //所属实例
    @ManyToOne
    @JoinColumn(name = "instance_id")
    private ApplicationInstance instance;
    //是否正常
    @Column(name = "normal")
    private boolean normal;

    /**
     * 消耗时间 ms
     */
    @Column(name = "cost_time")
    private long costTime;

    /**
     * 响应返回的数据长度: byte
     */
    @Column(name = "response_size")
    private long responseSize;


    //备注信息
    @Column(name = "remark")
    private String remark;

    //default
    public FrequencyMonitorLog() {
    }

    public ApplicationInstance instance() {
        return instance;
    }

    public FrequencyMonitorLog instance(ApplicationInstance instance) {
        this.instance = instance;
        return this;
    }

    public boolean normal() {
        return normal;
    }

    public FrequencyMonitorLog normal(boolean normal) {
        this.normal = normal;
        return this;
    }

    public long costTime() {
        return costTime;
    }

    public FrequencyMonitorLog costTime(long costTime) {
        this.costTime = costTime;
        return this;
    }

    public String remark() {
        return remark;
    }

    public FrequencyMonitorLog remark(String remark) {
        this.remark = remark;
        return this;
    }

    public FrequencyMonitorLog createTime(Date createTime) {
        this.createTime = createTime;
        return this;
    }

    public long responseSize() {
        return responseSize;
    }

    public FrequencyMonitorLog responseSize(long responseSize) {
        this.responseSize = responseSize;
        return this;
    }


    @Override
    public String toString() {
        return "{" +
                "normal=" + normal +
                ", id=" + id +
                ", createTime=" + createTime +
                ", costTime=" + costTime +
                ", responseSize=" + responseSize +
                ", remark='" + remark + '\'' +
                '}';
    }
}

src/main/java/com/andaily/hb/domain/log/reminder/AbstractPerMonitoringReminderSender.java
package com.andaily.hb.domain.log.reminder;

import com.andaily.hb.domain.application.ApplicationInstance;
import com.andaily.hb.domain.log.FrequencyMonitorLog;
import com.andaily.hb.domain.shared.Application;
import com.andaily.hb.infrastructure.DateUtils;

import java.util.HashMap;
import java.util.Map;

/**
 * 2016/5/19
 *
 * @author Shengzhao Li
 */
public abstract class AbstractPerMonitoringReminderSender implements PerMonitoringReminderSender {

    private static final String INSTANCE_MONITORING_URL = "monitoring/%s.hb";


    protected String instanceUrl(String instanceGuid) {
        String url = String.format(INSTANCE_MONITORING_URL, instanceGuid);
        return Application.host() + url;
    }


    protected Map<String, Object> contentModel(FrequencyMonitorLog monitorLog) {
        final ApplicationInstance instance = monitorLog.instance();

        Map<String, Object> model = new HashMap<>();
        model.put("instanceName", instance.instanceName());
        model.put("url", instance.monitorUrl());
        model.put("costTime", monitorLog.costTime());
        model.put("time", DateUtils.toDateText(monitorLog.createTime(), DateUtils.DEFAULT_DATE_TIME_FORMAT));
        model.put("instanceUrl", instanceUrl(instance.guid()));
        model.put("host", Application.host());
        model.put("remark", monitorLog.remark());
        return model;
    }


}

src/main/java/com/andaily/hb/domain/log/reminder/PerMonitoringReminderSender.java
package com.andaily.hb.domain.log.reminder;

import com.andaily.hb.domain.log.FrequencyMonitorLog;
import com.andaily.hb.domain.log.MonitoringReminderLog;

/**
 * @author Shengzhao Li
 */
public interface PerMonitoringReminderSender {


    public boolean support(FrequencyMonitorLog monitorLog);

    public void send(MonitoringReminderLog reminderLog, FrequencyMonitorLog monitorLog);

}

src/main/java/com/andaily/hb/web/controller/LogController.java
package com.andaily.hb.web.controller;

import com.andaily.hb.domain.dto.log.FrequencyMonitorLogListDto;
import com.andaily.hb.domain.dto.log.ReminderLogListDto;
import com.andaily.hb.service.LogService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;

/**
 * 15-2-13
 *
 * @author Shengzhao Li
 */
@Controller
@RequestMapping("log/")
public class LogController {


    @Autowired
    private LogService logService;


    //监控日志
    @RequestMapping("list.hb")
    public String listLogs(FrequencyMonitorLogListDto listDto, Model model) {
        logService.loadFrequencyMonitorLogListDto(listDto);
        model.addAttribute("listDto", listDto);
        return "log/log_list";
    }


    //提醒日志
    @RequestMapping("reminder_list.hb")
    public String reminderLogs(ReminderLogListDto listDto, Model model) {
        logService.loadReminderLogListDto(listDto);
        model.addAttribute("listDto", listDto);
        return "log/reminder_logs";
    }

}

src/main/webapp/WEB-INF/jsp/log/log_list.jsp
<%--
 * 
 * @author Shengzhao Li
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fun" uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib tagdir="/WEB-INF/tags" prefix="custom" %>
<%@ taglib prefix="dis" uri="http://displaytag.sf.net" %>
<!DOCTYPE HTML>
<html>
<head>
    <title>监控日志</title>
</head>
<body>
<%--Alert--%>
<%--<div class="row">--%>
<%--<div class="col-md-12">--%>
<%--<div class="alert alert-success" style="display: none;">--%>
<%--<button type="button" class="close" data-dismiss="alert">&times;</button>--%>
<%--<div><em class="fui-check-circle"></em>--%>
<%--<span id="saveInstanceOK" style="display: none;">Save instance successful</span>--%>
<%--</div>--%>
<%--</div>--%>
<%----%>
<%--</div>--%>
<%--</div>--%>
<div class="row">
    <div class="col-md-10">
        <form class="form-inline" role="form" action="" id="filterForm">
            <div class="form-group">
                <select name="instanceGuid" class="form-control">
                    <option value="">所有实例</option>
                    <c:forEach items="${listDto.instanceDtos}" var="st">
                        <option value="${st.guid}" ${st.guid eq listDto.instanceGuid?'selected':''}>${st.instanceName}</option>
                    </c:forEach>
                </select>
            </div>
            <div class="form-group">
                <select name="normal" class="form-control">
                    <option value="0">所有状态</option>
                    <option value="1" ${listDto.normal eq 1?'selected':''}>正常</option>
                    <option value="2" ${listDto.normal eq 2?'selected':''}>不正常</option>
                </select>
            </div>
            <div class="form-group">
                <div class="input-group">
                    <div class="input-group-addon">排序</div>
                    <select name="orderItem" class="form-control">
                        <c:forEach items="${listDto.orderItems}" var="item">
                            <option value="${item.value}" ${item eq listDto.orderItem?'selected':''}>${item.label}</option>
                        </c:forEach>
                    </select>
                </div>
            </div>
            <button type="submit" class="btn"><i class="fui-search"></i></button>
            <strong>${listDto.totalSize}</strong>条监控日志
        </form>
    </div>
    <div class="col-md-2">
        &nbsp;
    </div>
</div>

<c:if test="${not empty listDto.instanceDto}">
    <custom:log_instance_details d="${listDto.instanceDto}"/>
</c:if>

<div class="row">
    <div class="col-md-12">
        <table class="table table-striped table-hover">
            <thead>
            <tr>
                <th>实例名称</th>
                <th>日志时间</th>
                <th><abbr title='连接用时(ms)'>连接用时(ms)</abbr></th>
                <th><abbr title='响应数据大小(KB)'>响应数据大小(KB)</abbr></th>
                <th>备注</th>
            </tr>
            </thead>
            <tbody>
            <c:forEach items="${listDto.listGroupResults}" var="gro">
                <tr>
                    <td colspan="5">
                        <strong class="text-info">${gro.key}</strong>
                    </td>
                </tr>
                <c:forEach items="${gro.results}" var="d">
                    <tr class="${d.normal?'':'text-danger'}">
                        <td><a href="${contextPath}/monitoring/${d.instanceGuid}.hb">${d.instanceName}</a></td>
                        <td>${d.createTime}</td>
                        <td>${d.costTime}</td>
                        <td>${d.responseSizeAsKB}</td>
                        <td>
                            <custom:substring_remark d="${d}"/>
                        </td>
                    </tr>
                </c:forEach>
            </c:forEach>
            </tbody>
        </table>


        <dis:table list="${listDto}" id="d" form="filterForm" class="table hidden">
            <dis:column property="guid"/>
        </dis:table>

        <p class="help-block">
            <strong>提示</strong>: 系统将自动清理超出${listDto.cleanMonitorLogFrequency}天的监控日志
        </p>
    </div>
</div>

</body>
</html>

src/main/webapp/WEB-INF/jsp/log/reminder_logs.jsp
<%--
 * 
 * @author Shengzhao Li
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fun" uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib tagdir="/WEB-INF/tags" prefix="custom" %>
<%@ taglib prefix="dis" uri="http://displaytag.sf.net" %>
<!DOCTYPE HTML>
<html>
<head>
    <title>提醒日志</title>
</head>
<body>

<div class="row">
    <div class="col-md-10">
        <form class="form-inline" role="form" action="" id="filterForm">
            <div class="form-group">
                <select name="instanceGuid" class="form-control">
                    <option value="">所有实例</option>
                    <c:forEach items="${listDto.instanceDtos}" var="st">
                        <option value="${st.guid}" ${st.guid eq listDto.instanceGuid?'selected':''}>${st.instanceName}</option>
                    </c:forEach>
                </select>
            </div>
            <div class="form-group">
                <select name="normal" class="form-control">
                    <option value="-1">所有状态变化</option>
                    <option value="0" ${listDto.normal eq 0?'selected':''}>正常 -> 不正常</option>
                    <option value="1" ${listDto.normal eq 1?'selected':''}>不正常 -> 正常</option>
                </select>
            </div>
            <button type="submit" class="btn"><i class="fui-search"></i></button>
            <strong>${listDto.totalSize}</strong>条提醒日志
        </form>
    </div>
    <div class="col-md-2">
        &nbsp;
    </div>
</div>

<c:if test="${not empty listDto.instanceDto}">
    <custom:log_instance_details d="${listDto.instanceDto}"/>
</c:if>

<div class="row">
    <div class="col-md-12">
        <dis:table list="${listDto}" id="d" form="filterForm" class="table table-striped table-hover">
            <dis:column title="实例名称">
                <a href="${contextPath}/monitoring/${d.instanceGuid}.hb">${d.instanceName}</a>
            </dis:column>
            <dis:column title="提醒时间" property="createTime"/>
            <dis:column title="状态">
                <c:if test="${d.changeNormal}">
                    <em class="fui-checkbox-checked text-success" title="返回正常"></em>
                </c:if>
                <c:if test="${not d.changeNormal}">
                    <em class="fui-stumbleupon text-warning" title="变为不正常"></em>
                </c:if>
            </dis:column>
            <dis:column title="提醒邮箱">
                <a href="mailto:${d.receiveEmail}" class="text-info">${d.receiveEmail}</a>
                &nbsp;
                <a title="显示邮件内容" class="showMailContent" href="javascript:void(0)"><em
                        class="fui-mail"></em></a>

                <div class="hidden">
                        ${d.emailContent}
                </div>
            </dis:column>
            <dis:column title="微信号">
                <c:if test="${not empty d.openId}">
                    <span class="text-info">${d.openId}</span>
                    &nbsp;
                    <a title="Show WeChat Content" class="showWeChatContent" href="javascript:void(0)"><img
                            src="${contextPath}/static/images/wechat.jpg" class="img-rounded"
                            style="max-height: 20px;"/></a>

                    <div class="hidden">${d.weChartContent}</div>
                </c:if>
            </dis:column>
        </dis:table>
        <p class="help-block">
            <strong>提示</strong>: 系统将自动清理超出${listDto.cleanMonitorLogFrequency}天的提醒日志
        </p>
    </div>
</div>

<script>
    $(function () {
        new ReminderLogs();
    })
</script>
</body>
</html>