src/main/java/com/andaily/hb/domain/dto/user/ResetUserPasswordDto.java
package com.andaily.hb.domain.dto.user;

import com.andaily.hb.domain.dto.AbstractDto;
import com.andaily.hb.domain.user.User;

/**
 * @author Shengzhao Li
 */
public class ResetUserPasswordDto extends AbstractDto {

    private String newPassword;
    private String username;

    public ResetUserPasswordDto() {
    }

    public ResetUserPasswordDto(User user, String newPassword) {
        super(user.guid());
        this.newPassword = newPassword;
        this.username = user.username();
    }

    public String getNewPassword() {
        return newPassword;
    }

    public void setNewPassword(String newPassword) {
        this.newPassword = newPassword;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }
}

src/main/java/com/andaily/hb/domain/dto/user/SystemSettingDto.java
package com.andaily.hb.domain.dto.user;

import com.andaily.hb.domain.dto.AbstractDto;
import com.andaily.hb.domain.user.SystemSetting;

/**
 * 15-4-14
 *
 * @author Shengzhao Li
 */
public class SystemSettingDto extends AbstractDto {

    private static final long serialVersionUID = 2289700406929530627L;


    private boolean allowUserRegister;

    private int cleanMonitorLogFrequency;

    private long monitorLogAmount;

    /**
     * 是否启用 代理, 默认 false
     *
     * @since 2.0.1
     */
    private boolean proxyEnabled = false;

    /**
     * 代理 host
     *
     * @since 2.0.1
     */
    private String proxyHost;

    /**
     * 代理 port
     *
     * @since 2.0.1
     */
    private int proxyPort;

    public SystemSettingDto() {
    }

    public SystemSettingDto(SystemSetting setting) {
        super(setting.guid());
        this.allowUserRegister = setting.allowUserRegister();
        this.cleanMonitorLogFrequency = setting.cleanMonitorLogFrequency();

        this.proxyEnabled = setting.proxyEnabled();
        this.proxyHost = setting.proxyHost();
        this.proxyPort = setting.proxyPort();
    }


    public boolean isProxyEnabled() {
        return proxyEnabled;
    }

    public void setProxyEnabled(boolean proxyEnabled) {
        this.proxyEnabled = proxyEnabled;
    }

    public String getProxyHost() {
        return proxyHost;
    }

    public void setProxyHost(String proxyHost) {
        this.proxyHost = proxyHost;
    }

    public int getProxyPort() {
        return proxyPort;
    }

    public void setProxyPort(int proxyPort) {
        this.proxyPort = proxyPort;
    }

    public int getCleanMonitorLogFrequency() {
        return cleanMonitorLogFrequency;
    }

    public void setCleanMonitorLogFrequency(int cleanMonitorLogFrequency) {
        this.cleanMonitorLogFrequency = cleanMonitorLogFrequency;
    }

    public boolean isAllowUserRegister() {
        return allowUserRegister;
    }

    public void setAllowUserRegister(boolean allowUserRegister) {
        this.allowUserRegister = allowUserRegister;
    }

    public long getMonitorLogAmount() {
        return monitorLogAmount;
    }

    public void setMonitorLogAmount(long monitorLogAmount) {
        this.monitorLogAmount = monitorLogAmount;
    }
}

src/main/java/com/andaily/hb/domain/dto/user/UserDto.java
package com.andaily.hb.domain.dto.user;

import com.andaily.hb.domain.dto.AbstractDto;
import com.andaily.hb.domain.user.Privilege;
import com.andaily.hb.domain.user.User;
import com.andaily.hb.infrastructure.DateUtils;

import java.util.ArrayList;
import java.util.List;

/**
 * @author Shengzhao Li
 */
public class UserDto extends AbstractDto {

    private static final long serialVersionUID = -2716743335497591940L;
    protected String username;
    protected String createDate;

    protected String phone;
    protected String email;
    protected boolean defaultUser;

    protected List<Privilege> privileges = new ArrayList<>();
    protected boolean registerUser;

    public UserDto() {
    }

    public UserDto(User user) {
        super(user.guid());
        this.username = user.username();
        this.createDate = DateUtils.toDateText(user.createTime());

        this.phone = user.phone();
        this.email = user.email();
        this.defaultUser = user.defaultUser();

        this.privileges = user.privileges();
        this.registerUser = user.registerUser();
    }

    public boolean isRegisterUser() {
        return registerUser;
    }

    public void setRegisterUser(boolean registerUser) {
        this.registerUser = registerUser;
    }

    public boolean isDefaultUser() {
        return defaultUser;
    }

    public void setDefaultUser(boolean defaultUser) {
        this.defaultUser = defaultUser;
    }

    public List<Privilege> getPrivileges() {
        return privileges;
    }

    public void setPrivileges(List<Privilege> privileges) {
        this.privileges = privileges;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getCreateDate() {
        return createDate;
    }

    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public static List<UserDto> toDtos(List<User> users) {
        List<UserDto> dtoList = new ArrayList<>(users.size());
        for (User user : users) {
            dtoList.add(new UserDto(user));
        }
        return dtoList;
    }


    @Override
    public String toString() {
        final StringBuilder sb = new StringBuilder();
        sb.append("UserDto");
        sb.append("{username='").append(username).append('\'');
        sb.append(", createDate='").append(createDate).append('\'');
        sb.append(", phone='").append(phone).append('\'');
        sb.append(", email='").append(email).append('\'');
        sb.append(", defaultUser=").append(defaultUser);
        sb.append('}');
        return sb.toString();
    }
}

src/main/java/com/andaily/hb/domain/dto/user/UserFormDto.java
package com.andaily.hb.domain.dto.user;

import com.andaily.hb.domain.user.Privilege;
import com.andaily.hb.domain.user.User;
import com.andaily.hb.infrastructure.MatchUtils;
import com.andaily.hb.infrastructure.PasswordHandler;

import java.util.List;

/**
 * @author Shengzhao Li
 */
public class UserFormDto extends UserDto {

    private String password;
    private String rePassword;

    private String existUsername;

    public UserFormDto() {
    }

    public UserFormDto(User user) {
        super(user);
        this.existUsername = user.username();
    }

    @Override
    public boolean isNewly() {
        return super.isNewly() || MatchUtils.isCreate(guid);
    }

    public List<Privilege> getAllPrivileges() {
        return Privilege.authPrivileges();
    }


    public User toDomain() {
        String encryptPass = PasswordHandler.encryptPassword(password);
        return new User(username, encryptPass, phone, email);
    }


    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getRePassword() {
        return rePassword;
    }

    public void setRePassword(String rePassword) {
        this.rePassword = rePassword;
    }

    public String getExistUsername() {
        return existUsername;
    }

    public void setExistUsername(String existUsername) {
        this.existUsername = existUsername;
    }
}

src/main/java/com/andaily/hb/domain/dto/user/UserListDto.java
package com.andaily.hb.domain.dto.user;

import com.andaily.hb.domain.shared.paginated.DefaultPaginated;

import java.util.Map;

/**
 * @author Shengzhao Li
 */
public class UserListDto extends DefaultPaginated<UserDto> {


    private String username;


    public UserListDto() {
    }

    @Override
    public Map<String, Object> queryMap() {
        final Map<String, Object> map = super.queryMap();
        map.put("username", username);
        return map;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }
}

src/main/java/com/andaily/hb/domain/dto/user/UserProfileDto.java
package com.andaily.hb.domain.dto.user;

import com.andaily.hb.domain.dto.AbstractDto;

/**
 * @author Shengzhao Li
 */
public class UserProfileDto extends AbstractDto {

    private String oldPassword;
    private String password;
    private String rePassword;

    public UserProfileDto() {
    }

    public String getOldPassword() {
        return oldPassword;
    }

    public void setOldPassword(String oldPassword) {
        this.oldPassword = oldPassword;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getRePassword() {
        return rePassword;
    }

    public void setRePassword(String rePassword) {
        this.rePassword = rePassword;
    }
}

src/main/java/com/andaily/hb/domain/dto/user/UserRegisterDto.java
package com.andaily.hb.domain.dto.user;

import com.andaily.hb.domain.dto.AbstractDto;
import com.andaily.hb.domain.user.User;
import com.andaily.hb.infrastructure.PasswordHandler;

/**
 * @author Shengzhao Li
 */
public class UserRegisterDto extends AbstractDto {

    public static final String CAPTCHA_KEY = "captcha";


    private String username;
    private String password;
    private String rePassword;

    private String email;
    private String phone;

    public UserRegisterDto() {
    }


    public String getCaptchaKey() {
        return CAPTCHA_KEY;
    }


    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getRePassword() {
        return rePassword;
    }

    public void setRePassword(String rePassword) {
        this.rePassword = rePassword;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public User toDomain() {
        String encryptPass = PasswordHandler.encryptPassword(password);
        return new User(username, encryptPass, phone, email);
    }
}

src/main/java/com/andaily/hb/domain/dto/user/WeixinUserDto.java
package com.andaily.hb.domain.dto.user;

import com.andaily.hb.domain.dto.AbstractDto;
import com.andaily.hb.domain.user.WeixinUser;
import com.andaily.hb.infrastructure.DateUtils;

import java.util.ArrayList;
import java.util.List;

/**
 * 2016/5/17
 *
 * @author Shengzhao Li
 */
public class WeixinUserDto extends AbstractDto {
    private static final long serialVersionUID = -5456120599079765768L;

    private String createDate;
    private String openId;

    //HB 账号
    private String hbUsername;

    // 微信 用户的昵称
    private String nickName;

    public WeixinUserDto() {
    }

    public WeixinUserDto(WeixinUser weixinUser) {
        super(weixinUser.guid());
        this.openId = weixinUser.openId();
        this.createDate = DateUtils.toDateText(weixinUser.createTime());


        this.hbUsername = weixinUser.hbUsername();
        this.nickName = weixinUser.nickName();
    }


    public String getCreateDate() {
        return createDate;
    }

    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    public String getOpenId() {
        return openId;
    }

    public void setOpenId(String openId) {
        this.openId = openId;
    }

    public String getHbUsername() {
        return hbUsername;
    }

    public void setHbUsername(String hbUsername) {
        this.hbUsername = hbUsername;
    }

    public String getNickName() {
        return nickName;
    }

    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    public static List<WeixinUserDto> toDtos(List<WeixinUser> weixinUsers) {
        List<WeixinUserDto> dtos = new ArrayList<>(weixinUsers.size());
        for (WeixinUser weixinUser : weixinUsers) {
            dtos.add(new WeixinUserDto(weixinUser));
        }
        return dtos;
    }
}

src/main/java/com/andaily/hb/domain/dto/user/WeixinUserPaginated.java
package com.andaily.hb.domain.dto.user;

import com.andaily.hb.domain.shared.paginated.DefaultPaginated;

import java.util.Map;

/**
 * 2016/5/20
 *
 * @author Shengzhao Li
 */
public class WeixinUserPaginated extends DefaultPaginated<WeixinUserDto> {

    private String nickName;

    public WeixinUserPaginated() {
    }

    @Override
    public Map<String, Object> queryMap() {
        final Map<String, Object> map = super.queryMap();
        map.put("nickName", nickName);
        return map;
    }

    public String getNickName() {
        return nickName;
    }

    public void setNickName(String nickName) {
        this.nickName = nickName;
    }
}

src/main/java/com/andaily/hb/domain/user/Privilege.java
package com.andaily.hb.domain.user;

import java.util.Arrays;
import java.util.List;

/**
 * @author Shengzhao Li
 */

public enum Privilege {

    //Any user have the default privilege
    DEFAULT("Default"),

    CREATE_EDIT_INSTANCE("Create/Edit instance"),
    DELETE_INSTANCE("Delete instance"),
    START_STOP_INSTANCE("Start/Stop monitoring instance"),

    USER_MANAGEMENT("User management"),
    SYSTEM_SETTING("System setting");


    private String label;


    private Privilege(String label) {
        this.label = label;
    }

    public String getLabel() {
        return label;
    }

    public String getValue() {
        return name();
    }

    public static List<Privilege> authPrivileges() {
        return Arrays.asList(
                CREATE_EDIT_INSTANCE,
                DELETE_INSTANCE,
                START_STOP_INSTANCE,
                USER_MANAGEMENT,
                SYSTEM_SETTING
        );
    }

    public static List<Privilege> registeredUserPrivileges() {
        return Arrays.asList(
                CREATE_EDIT_INSTANCE,
                DELETE_INSTANCE,
                START_STOP_INSTANCE
        );
    }
}

src/main/java/com/andaily/hb/web/controller/UserController.java
package com.andaily.hb.web.controller;

import com.andaily.hb.domain.dto.user.ResetUserPasswordDto;
import com.andaily.hb.domain.dto.user.UserFormDto;
import com.andaily.hb.domain.dto.user.UserListDto;
import com.andaily.hb.domain.dto.user.WeixinUserPaginated;
import com.andaily.hb.service.UserService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.servlet.http.HttpServletResponse;
import javax.validation.Valid;
import java.io.IOException;

/**
 * @author Shengzhao Li
 */
@Controller
@RequestMapping("/user/")
public class UserController {


    @Autowired
    private UserService userService;


    @RequestMapping("list.hb")
    public String list(UserListDto listDto, Model model) {
        userService.loadUserListDto(listDto);
        model.addAttribute("listDto", listDto);
        return "user/user_list";
    }


    @RequestMapping("weixin_list.hb")
    public String weixinList(WeixinUserPaginated listDto, Model model) {
        userService.loadWeixinUserPaginated(listDto);
        model.addAttribute("listDto", listDto);
        return "user/weixin_user_list";
    }


    @RequestMapping(value = "form/{guid}.hb", method = RequestMethod.GET)
    public String loadForm(@PathVariable("guid") String guid, Model model) {
        UserFormDto formDto = userService.loadUserFormDto(guid);
        model.addAttribute("formDto", formDto);
        return "user/user_form";
    }

    @RequestMapping(value = "form/{guid}.hb", method = RequestMethod.POST)
    public String submitForm(@ModelAttribute("formDto") @Valid UserFormDto formDto, BindingResult result, Model model) {
        if (result.hasErrors()) {
            return "user/user_form";
        }
        userService.persistUserFormDto(formDto);
        model.addAttribute("alert", "saveUserOK");
        return "redirect:../list.hb";
    }

    /*
   * Delete user (logic delete)
   * */
    @RequestMapping(value = "delete/{guid}.hb", method = RequestMethod.POST)
    public void delete(@PathVariable("guid") String guid, HttpServletResponse response) throws Exception {
        userService.deleteUser(guid);
        responseOK(response);
    }

    private void responseOK(HttpServletResponse response) throws IOException {
        response.getWriter().print("ok");
    }


    /*
   * Reset password
   * */
    @RequestMapping(value = "reset_password/{guid}.hb", method = RequestMethod.POST)
    public String resetPassword(@PathVariable("guid") String guid, Model model) throws Exception {
        ResetUserPasswordDto resetUserPasswordDto = userService.resetUserPassword(guid);
        model.addAttribute("resetUserPasswordDto", resetUserPasswordDto);
        return "user/reset_password_result";
    }

}

src/main/webapp/WEB-INF/jsp/user/login.jsp
<%--
 * 
 * @author Shengzhao Li
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" trimDirectiveWhitespaces="true" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fun" uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ taglib tagdir="/WEB-INF/tags" prefix="custom" %>
<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8"/>
    <c:set var="contextPath" value="${pageContext.request.contextPath}" scope="application"/>

    <meta name="viewport" content="width=device-width,user-scalable=no"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
    <meta name="${_csrf.headerName}" content="${_csrf.token}"/>
    <meta name="keywords" content="HeartBeat "/>
    <meta name="description" content="HeartBeat "/>
    <meta name="author" content="andaily.com"/>


    <title><spring:message code="login.jsp.title" text="Sign in"/> - HeartBeat</title>


    <link href="${contextPath}/static/flat_ui/css/vendor/bootstrap.min.css" rel="stylesheet"/>
    <link href="${contextPath}/static/flat_ui/css/flat-ui.css" rel="stylesheet"/>
    <link rel="shortcut icon" href="${contextPath}/favicon.ico"/>

</head>
<body>


<div class="container" style="margin-top: 1%;">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">

            <div class="login">
                <div class="login-screen">
                    <div class="login-icon">
                        <a href="${contextPath}/" class="text-warning"><h3>HB</h3></a>
                        <a href="${contextPath}/static/images/qiuchang8_qrcode.jpg" target="_blank"><img
                                src="${contextPath}/static/images/qiuchang8_qrcode.jpg"
                                class="img-rounded img-responsive"/></a>
                    </div>

                    <div class="login-form">
                        <form action="${contextPath}/login" method="post">
                            <custom:csrf/>
                            <div class="control-group">
                                <input type="text" name="username" class="login-field form-control" id="username"
                                       placeholder="<spring:message code="login.jsp.username" text="Username"/>"
                                       required="required" maxlength="255" autocomplete="off"/>
                                <label class="login-field-icon fui-user" for="username"></label>
                            </div>
                            <div class="control-group">
                                <input type="password" name="password" class="login-field form-control" id="password"
                                       placeholder="<spring:message code="login.jsp.password" text="Password"/>"
                                       required="required" maxlength="255"/>
                                <label class="login-field-icon fui-lock" for="password"></label>
                            </div>

                            <button class="btn btn-primary btn-large btn-block" type="submit"><spring:message
                                    code="login.jsp.sign.in" text="Sign in"/></button>

                            <span class="text-danger pull-right" style="font-size: 13px;margin-top: 15px;">
                                <c:if test="${param.error eq '1'}"><em
                                        class="fui-alert-circle"></em> <spring:message code="login.jsp.failed"
                                                                                       text="Sign in failed"/></c:if>
                                <c:if test="${param.error eq '2'}"><em
                                        class="fui-alert-circle"></em> <spring:message code="login.jsp.access.denied"
                                                                                       text="Access denied"/></c:if>
                            </span>
                            <c:if test="${allowRegister}">
                                <a class="login-link" href="${contextPath}/register.hb">&raquo; <spring:message
                                        code="login.jsp.register" text="Register"/></a>
                            </c:if>
                        </form>
                    </div>
                </div>

                <div class="text-center">
                    <a target="_blank" href="${projectHome}"
                       style="font-size: 14px;text-decoration: underline;">HeartBeat&nbsp;
                        ${currentVersion}</a>
                </div>
            </div>

        </div>
    </div>
</div>
</body>
</html>

src/main/webapp/WEB-INF/jsp/user/reset_password_result.jsp
<%--
 * 
 * @author Shengzhao Li
--%>

<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fun" uri="http://java.sun.com/jsp/jstl/functions" %>

<div>
    <em class="fui-check-circle"></em>
    重置密码功能!<br/>
    该用户[${resetUserPasswordDto.username}] 的新密码为 <strong
        class="label label-info">${resetUserPasswordDto.newPassword}</strong>.
</div>

src/main/webapp/WEB-INF/jsp/user/user_form.jsp
<%--
 * 
 * @author Shengzhao Li
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fun" uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<!DOCTYPE HTML>
<html>
<head>
    <title>${formDto.newly?'添加':'编辑'}用户</title>
</head>
<body>
<div>
    <div class="row">
        <div class="col-md-12">
            <h4>${formDto.newly?'添加':'编辑'}用户</h4>
            <form:form commandName="formDto" cssClass="form-horizontal">
                <form:hidden path="existUsername"/>
                <div class="form-group">
                    <label for="username" class="col-sm-2 control-label">账号</label>

                    <div class="col-sm-8">
                        <form:input path="username" id="username" cssClass="form-control" autocomplete="off"
                                    placeholder="请输入账号" required="true" maxlength="255"/>
                        <p class="help-block">账号必须唯一</p>
                        <form:errors path="username" cssClass="text-danger"/>
                    </div>
                </div>
                <c:if test="${formDto.newly}">
                    <div class="form-group">
                        <label for="password" class="col-sm-2 control-label">密码</label>

                        <div class="col-sm-8">
                            <form:password path="password" id="password" cssClass="form-control"
                                           placeholder="请输入密码" required="true" maxlength="255"/>
                            <p class="help-block">密码长度 >= 6</p>
                            <form:errors path="password" cssClass="text-danger"/>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="rePassword" class="col-sm-2 control-label">重复密码</label>

                        <div class="col-sm-8">
                            <form:password path="rePassword" id="rePassword" cssClass="form-control"
                                           placeholder="请再次输入密码" required="true" maxlength="255"/>
                            <p class="help-block">再次输入相同的密码</p>
                            <form:errors path="rePassword" cssClass="text-danger"/>
                        </div>
                    </div>
                </c:if>
                <div class="form-group">
                    <label for="email" class="col-sm-2 control-label">邮箱</label>

                    <div class="col-sm-8">
                        <form:input path="email" id="email" cssClass="form-control"
                                    placeholder="请输入邮箱" maxlength="255"/>
                        <p class="help-block">用户的邮箱, 可选.</p>
                        <form:errors path="email" cssClass="text-danger"/>
                    </div>
                </div>
                <div class="form-group">
                    <label for="phone" class="col-sm-2 control-label">电话</label>

                    <div class="col-sm-8">
                        <form:input path="phone" id="phone" cssClass="form-control"
                                    placeholder="请输入电话" maxlength="255"/>
                        <p class="help-block">用户的电话号码, 可选.</p>
                        <form:errors path="phone" cssClass="text-danger"/>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label">权限</label>

                    <div class="col-sm-8">
                        <c:forEach items="${formDto.allPrivileges}" var="p">
                            <label class="toggle-checkbox">
                                <input type="checkbox" name="privileges"
                                       value="${p.value}" ${fun:contains(formDto.privileges, p)?'checked':''}/> ${p.label}
                            </label>
                        </c:forEach>
                        <p class="help-block">用户的权限, 至少勾选一个.</p>
                        <form:errors path="privileges" cssClass="text-danger"/>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-primary"><em class="fui-check-circle"></em> 保存
                        </button>
                        &nbsp;<a href="../list.hb">取消</a>
                    </div>
                </div>
            </form:form>
        </div>
    </div>
</div>

</body>
</html>

src/main/webapp/WEB-INF/jsp/user/weixin_user_list.jsp
<%--
 * 
 * @author Shengzhao Li
--%>

<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fun" uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib tagdir="/WEB-INF/tags" prefix="custom" %>
<%@ taglib prefix="dis" uri="http://displaytag.sf.net" %>
<!DOCTYPE HTML>
<html>
<head>
    <title>微信用户</title>
</head>
<body>
<%--Alert--%>
<%--<div class="row">--%>
<%--<div class="col-md-12">--%>
<%--<div class="alert alert-success" style="display: none;">--%>
<%--<button type="button" class="close" data-dismiss="alert">&times;</button>--%>
<%--<div><em class="fui-check-circle"></em>--%>
<%--<span id="saveUserOK" style="display: none;">Save user successful</span>--%>
<%--<span id="deleteSuccess" style="display: none;">Delete user successful</span>--%>
<%--</div>--%>
<%--</div>--%>
<%--</div>--%>
<%--</div>--%>

<div class="row">
    <div class="col-md-8">
        <form class="form-inline" role="form" action="" id="filterForm">
            <div class="input-group">
                <input type="text" name="nickName" value="${listDto.nickName}" placeholder="输入昵称"
                       class="form-control"/>
                <span class="input-group-btn">
                    <button type="submit" class="btn"><i class="fui-search"></i></button>
                </span>
            </div>
            <strong>${listDto.totalSize}</strong>个微信用户
        </form>
    </div>
    <div class="col-md-4">
    </div>
</div>


<div class="row">
    <div class="col-md-12">
        <dis:table list="${listDto}" id="d" form="filterForm" class="table table-striped table-hover">
            <dis:column title="OpenId" property="openId"/>
            <dis:column title="昵称" property="nickName"/>
            <dis:column title="HB账号" property="hbUsername"/>
            <dis:column title="添加日期" property="createDate"/>
        </dis:table>
    </div>
</div>


</body>
</html>