src/main/java/com/andaily/hb/domain/dto/HBSearchDto.java
package com.andaily.hb.domain.dto;

import com.andaily.hb.domain.shared.paginated.DefaultPaginated;
import com.andaily.hb.service.operation.search.ApplicationInstanceSearcher;
import com.andaily.hb.service.operation.search.HBSearcher;
import com.andaily.hb.service.operation.search.MonitorLogSearcher;

import java.util.Map;

/**
 * 15-3-13
 *
 * @author Shengzhao Li
 */
public class HBSearchDto extends DefaultPaginated<HBSearchResultDto> {

    private static final HBSearchType DEFAULT_SEARCH_TYPE = HBSearchType.INSTANCE;

    private String key;
    private HBSearchType searchType = DEFAULT_SEARCH_TYPE;

    public HBSearchDto() {
    }

    @Override
    public Map<String, Object> queryMap() {
        final Map<String, Object> map = super.queryMap();
        map.put("key", key);
        return map;
    }

    public HBSearchType[] getSearchTypes() {
        return HBSearchType.values();
    }

    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    public HBSearchType getSearchType() {
        if (searchType == null) {
            return DEFAULT_SEARCH_TYPE;
        }
        return searchType;
    }

    public void setSearchType(HBSearchType searchType) {
        this.searchType = searchType;
    }

    public static enum HBSearchType {
        INSTANCE("实例") {
            @Override
            public HBSearcher resolveSearcher() {
                return new ApplicationInstanceSearcher();
            }
        },
        MONITOR_LOG("监控日志") {
            @Override
            public HBSearcher resolveSearcher() {
                return new MonitorLogSearcher();
            }
        };

        private String label;

        private HBSearchType(String label) {
            this.label = label;
        }

        public abstract HBSearcher resolveSearcher();


        public boolean isInstance() {
            return INSTANCE.equals(this);
        }

        public boolean isMonitorLog() {
            return MONITOR_LOG.equals(this);
        }

        public String getLabel() {
            return label;
        }
    }
}

src/main/java/com/andaily/hb/domain/dto/IndexDto.java
package com.andaily.hb.domain.dto;

import java.util.ArrayList;
import java.util.List;

/**
 * @author Shengzhao Li
 */
public class IndexDto extends AbstractDto {

    private static final long serialVersionUID = 8105351173324456654L;
    //default show latest 20  times data
    private int maxResult = 20;

    private boolean enabled = true;

    private List<IndexInstanceDto> instanceDtos = new ArrayList<>();


    public IndexDto() {
    }

    public List<IndexInstanceDto> getInstanceDtos() {
        return instanceDtos;
    }

    public boolean isEmployInstances() {
        return instanceDtos.isEmpty();
    }

    public int getMaxResult() {
        return maxResult;
    }

    public void setMaxResult(int maxResult) {
        this.maxResult = maxResult;
    }

    public boolean isEnabled() {
        return enabled;
    }

    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }
}

src/main/webapp/WEB-INF/jsp/index.jsp
<%--
 * 
 * @author Shengzhao Li
--%>

<%@ page contentType="text/html;charset=UTF-8" language="java" trimDirectiveWhitespaces="true" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<!DOCTYPE HTML>
<html>
<head>
    <title><spring:message code="index.jsp.title" text="Monitoring"/></title>
    <c:set var="contextPath" value="${pageContext.request.contextPath}" scope="application"/>
</head>
<body>
<c:if test="${indexDto.employInstances}" var="emptyInstances">
    <div class="row">
        <div class="col-md-12">
            <div class="alert alert-info" role="alert">
                <strong class="fui-info-circle"></strong>
                <spring:message code="index.jsp.empty.instances"
                                text="Not enabled any instance to monitoring yet. Now create the first"/> <a
                    href="${contextPath}/instance/instance_form.hb"><spring:message code="index.jsp.new.instance"
                                                                                    text="new instance"/></a>
                <spring:message code="index.jsp.or.go.to" text="or go to"/> <a
                    href="${contextPath}/instance/list.hb"><spring:message code="index.jsp.instances"
                                                                           text="instances"/></a> <spring:message
                    code="index.jsp.enable.it" text="enable it."/>
            </div>
        </div>
    </div>
</c:if>

<c:if test="${not emptyInstances}">
    <div class="row">
        <div class="col-md-10">
            <form class="form-inline" role="form" action="" id="filterForm">
                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-addon"><spring:message code="index.jsp.per.show" text="Per show"/></div>
                        <select name="maxResult" class="form-control">
                            <c:forEach begin="10" end="50" step="10" var="i">
                                <option value="${i}" ${i == indexDto.maxResult?'selected':''}>${i}</option>
                            </c:forEach>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <div class="checkbox">
                        <label>
                            <input type="checkbox" id="enabled" ${indexDto.enabled?'checked':''}/><spring:message
                                code="index.jsp.monitoring" text="Monitoring"/>
                            <input type="hidden" name="enabled" value="${indexDto.enabled}"/>
                        </label>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-md-2">
            <div class="pull-right">
                <strong>${indexDto.instanceDtos.size()}</strong> <spring:message code="index.jsp.instances.total"
                                                                                 text="instance(s)"/>
            </div>
        </div>
    </div>

    <c:forEach items="${indexDto.instanceDtos}" var="ins" varStatus="s">
        <div class="row">
            <hr/>
            <div class="col-md-12">
                <h4><c:if test="${ins.enabled}"><em class="fui-time text-success" title="监控中"></em></c:if>
                    <c:if test="${ins.privateInstance}"> <em class="fui-lock text-muted" title="私有实例"></em></c:if>
                    <c:if test="${ins.useProxy}">&nbsp;<em class="fui-loop text-info" title="使用代理"></em>&nbsp;</c:if>
                    <a href="${contextPath}/monitoring/${ins.guid}.hb">${ins.instanceName}</a>
                    <small><a href="${ins.monitorUrl}" target="_blank" class="text-muted">${ins.monitorUrl}</a>
                        [${ins.requestMethod}]
                    </small>
                </h4>

                <div id="chart${s.index}" style="height:300px"></div>
            </div>
        </div>

    </c:forEach>

    <script src="${contextPath}/static/js/echarts/echarts.js"></script>
    <script>
        require.config({
            paths: {
                echarts: '${contextPath}/static/js/echarts'
            }
        });
        require(
            [
                'echarts',
                'echarts/chart/bar',
                'echarts/chart/line'
            ],
            function (ec) {
                <c:forEach items="${indexDto.instanceDtos}" var="ins" varStatus="s">
                var option${s.index} = {
                    title: {
                        text: '${ins.instanceName}',
                        subtext: '<spring:message code="index.jsp.frequency" text="Frequency"/>: ${ins.frequency.label}  <spring:message code="index.jsp.max.conn" text="Max-Conn"/>: ${ins.maxConnectionSeconds}s <spring:message code="index.jsp.request.method" text="Request-Method"/>: ${ins.requestMethod} <spring:message code="index.jsp.failed.time" text="ContinueFailedTimes"/>: ${ins.continueFailedTimes}'
                    },
                    tooltip: {
                        trigger: 'axis'
                    },
                    legend: {
                        data: ['<spring:message code="index.jsp.conn.time" text="Conn Time(ms)"/>']
                    },
                    toolbox: {
                        show: true,
                        feature: {
                            mark: {show: false},
                            dataView: {show: false, readOnly: false},
                            magicType: {show: true, type: ['line', 'bar']},
                            restore: {show: true},
                            saveAsImage: {show: true}
                        }
                    },
                    xAxis: [
                        {
                            type: 'category',
                            data:${ins.categoryData}
                        }
                    ],
                    yAxis: [
                        {
                            type: 'value'
                        }
                    ],
                    series: [
                        {
                            name: '<spring:message code="index.jsp.conn.time" text="Conn Time(ms)"/>',
                            type: 'line',
                            data:${ins.seriesData},
                            markLine: {
                                data: [
                                    {
                                        type: 'average',
                                        name: '<spring:message code="index.jsp.average.conn.time" text="Average Conn Time"/>'
                                    }
                                ]
                            }
                        }
                    ]
                };

                var myChart${s.index} = ec.init(document.getElementById('chart${s.index}'));
                myChart${s.index}.setOption(option${s.index});
                myChart${s.index}.setTheme('macarons');

                var lastLogDate${s.index} = '${ins.lastLogDate}';
                setInterval(function () {
                    $.get("load_addition_monitor_logs.hb", {
                        lastLogDate: lastLogDate${s.index},
                        guid: '${ins.guid}'
                    }, function (data) {
                        myChart${s.index}.addData(eval(data.additionData));
                        lastLogDate${s.index} = data.lastLogDate;
                    });

                }, ${ins.intervalTime});
                </c:forEach>
            }
        );

    </script>
</c:if>

<script>
    $(function () {
        new Index('${param.alert}');
    });
</script>
</body>
</html>

src/main/webapp/WEB-INF/jsp/monitoring_instance.jsp
<%--
 * 
 * @author Shengzhao Li
--%>

<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<!DOCTYPE HTML>
<html>
<head>
    <c:set var="contextPath" value="${pageContext.request.contextPath}" scope="application"/>
    <title><spring:message code="monitoring.instance.jsp.title" text="Monitoring"/>
        [${instanceDto.instanceName}]</title>
</head>
<body>

<div class="row">
    <h4><c:if test="${instanceDto.enabled}"><em class="fui-time text-success"
                                                title="<spring:message code="monitoring.instance.jsp.title" text="Monitoring"/>"></em></c:if>
        <c:if test="${instanceDto.privateInstance}"><em class="fui-lock text-muted" title="私有实例"></em></c:if>
        <c:if test="${instanceDto.useProxy}"><em class="fui-loop text-info" title="使用代理"></em></c:if>
        ${instanceDto.instanceName}</h4>

    <div class="col-md-12">
        <div id="chart" style="height:400px"></div>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <ul class="list-group">
            <li class="list-group-item">
                <spring:message code="monitoring.instance.jsp.monitor.url" text="Monitor URL"/>: <a
                    href="${instanceDto.monitorUrl}"
                    target="_blank">${instanceDto.monitorUrl}</a> <span
                    class="text-info">[${instanceDto.requestMethod}]</span>
            </li>
            <c:if test="${not empty instanceDto.contentType}">
                <li class="list-group-item">
                    <spring:message code="monitoring.instance.jsp.contenttype" text="ContentType"/>: <span
                        class="text-info">${instanceDto.contentType}</span>
                </li>
            </c:if>
            <li class="list-group-item">
                <spring:message code="monitoring.instance.jsp.frequency" text="Frequency"/>: <span
                    class="text-info">${instanceDto.frequency.label}</span>
            </li>
            <li class="list-group-item">
                <abbr title='<spring:message code="monitoring.instance.jsp.max.connection.time" text="Max Connection Time(s)"/>'><spring:message
                        code="monitoring.instance.jsp.max.conn"
                        text="Max Conn(s)"/></abbr>: <span
                    class="text-info">${instanceDto.maxConnectionSeconds}s</span>
            </li>
            <li class="list-group-item">
                <spring:message code="monitoring.instance.jsp.email" text="Email"/>: <span
                    class="text-info">${instanceDto.email}</span>
            </li>
            <c:if test="${not empty instanceDto.weixinUserDtos}">
                <li class="list-group-item">
                    WeChat: <span class="text-info"><c:forEach items="${instanceDto.weixinUserDtos}" var="wu"
                                                               varStatus="vs">${wu.nickName}${vs.last?'':','}</c:forEach></span>
                </li>
            </c:if>
            <li class="list-group-item">
                <spring:message code="monitoring.instance.jsp.remark" text="Remark"/>: <span
                    class="text-info">${instanceDto.remark}</span>
            </li>
        </ul>
    </div>
    <div class="col-md-6">
        <img src="${contextPath}/static/images/loading_64.gif" class="img-responsive"/>
        <%--Ajax load data--%>
        <div id="staticsDiv"></div>
    </div>
</div>


<div class="row">
    <div class="col-md-12">
        <div class="text-center">
            <a href="javascript:history.back();" class="btn btn-inverse"><spring:message
                    code="monitoring.instance.jsp.back" text="Back"/></a>
        </div>
    </div>
</div>


<script src="${contextPath}/static/js/echarts/echarts.js"></script>
<script>
    require.config({
        paths: {
            echarts: '${contextPath}/static/js/echarts'
        }
    });
    require(
            [
                'echarts',
                'echarts/chart/bar',
                'echarts/chart/line'
            ],
            function (ec) {

                var option0 = {
                    title: {
                        text: '${instanceDto.instanceName}',
                        subtext: '<spring:message code="monitoring.instance.jsp.frequency" text="Frequency"/>: ${instanceDto.frequency.label}  <spring:message code="monitoring.instance.jsp.max.conn2" text="Max-Conn"/>: ${instanceDto.maxConnectionSeconds}s <spring:message code="monitoring.instance.jsp.request.method" text="Request-Method"/>: ${instanceDto.requestMethod} <spring:message code="index.jsp.failed.time" text="ContinueFailedTimes"/>: ${instanceDto.continueFailedTimes}'
                    },
                    tooltip: {
                        trigger: 'axis'
                    },
                    legend: {
                        data: ['<spring:message code="monitoring.instance.jsp.conn.time" text="Conn Time(ms)"/>']
                    },
                    toolbox: {
                        show: true,
                        feature: {
                            mark: {show: false},
                            dataView: {show: false, readOnly: false},
                            magicType: {show: true, type: ['line', 'bar']},
                            restore: {show: true},
                            saveAsImage: {show: true}
                        }
                    },
                    xAxis: [
                        {
                            type: 'category',
                            data:${instanceDto.categoryData}
                        }
                    ],
                    yAxis: [
                        {
                            type: 'value'
                        }
                    ],
                    series: [
                        {
                            name: '<spring:message code="monitoring.instance.jsp.conn.time" text="Conn Time(ms)"/>',
                            type: 'line',
                            data:${instanceDto.seriesData},
                            markLine: {
                                data: [
                                    {
                                        type: 'average',
                                        name: '<spring:message code="monitoring.instance.jsp.average.conn.time" text="Average Conn Time"/>'
                                    }
                                ]
                            }
                        }
                    ]
                };

                var myChart0 = ec.init(document.getElementById('chart'));
                myChart0.setOption(option0);
                myChart0.setTheme('macarons');

                var lastLogDate0 = '${instanceDto.lastLogDate}';
                setInterval(function () {
                    $.get("../load_addition_monitor_logs.hb", {
                        lastLogDate: lastLogDate0,
                        guid: '${instanceDto.guid}'
                    }, function (data) {
                        myChart0.addData(eval(data.additionData));
                        lastLogDate0 = data.lastLogDate;
                    });

                }, ${instanceDto.intervalTime});
            }
    );

    new MonitoringInstance('${instanceDto.guid}');
</script>

</body>
</html>

src/main/webapp/WEB-INF/jsp/search_result.jsp
<%--
 * 
 * @author Shengzhao Li
--%>

<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="dis" uri="http://displaytag.sf.net" %>
<%@ taglib tagdir="/WEB-INF/tags" prefix="custom" %>
<!DOCTYPE HTML>
<html>
<head>
    <title>搜索结果 [${searchDto.key}]</title>

    <style>
        .list-group li:hover {
            background-color: #f9f9f9;
        }
    </style>
</head>
<body>

<div class="row">
    <div class="col-md-12">
        <form class="form-inline" role="form" action="" id="filterForm">
            <div class="input-group">
                <input type="text" name="key" value="${searchDto.key}" class="form-control" placeholder="搜索"/>
                 <span class="input-group-btn">
                       <button type="submit" class="btn"><span class="fui-search"></span></button>
                  </span>
            </div>
            <input type="hidden" id="searchType" name="searchType" value="${searchDto.searchType}"/>
            共<strong>${searchDto.totalSize}</strong>条数据
        </form>
    </div>
</div>

<div class="row" style="margin-top: 10px;">
    <div class="col-md-12">
        <ul class="nav nav-tabs">
            <c:forEach items="${searchDto.searchTypes}" var="t">
                <li role="presentation" class="${t eq searchDto.searchType?'active':''}"><a
                        href="javascript:void(0);" sType=${t}>${t.label}</a>
                </li>
            </c:forEach>
        </ul>
        <div style="margin-top: 5px;">
            <%--instance--%>
            <c:if test="${searchDto.searchType.instance}">
                <c:if test="${empty searchDto.list}">
                    <div class="well well-sm text-muted">无搜索结果</div>
                </c:if>
                <c:if test="${not empty searchDto.list}">
                    <ul class="list-group">
                        <c:forEach items="${searchDto.list}" var="d">
                            <custom:instance_group_item d="${d.instanceDto}"/>
                        </c:forEach>
                    </ul>
                    <%--pagination--%>
                    <dis:table list="${searchDto}" id="d" form="filterForm"
                               class="table table-striped table-hover hidden">
                        <dis:column property="guid"/>
                    </dis:table>
                </c:if>
            </c:if>

            <%--monitorLog--%>
            <c:if test="${searchDto.searchType.monitorLog}">
                <dis:table list="${searchDto}" id="d" form="filterForm" class="table table-striped table-hover">
                    <dis:column title="实例" class="${d.monitorLogDto.normal?'':'text-danger'}">
                        <a href="${contextPath}/monitoring/${d.monitorLogDto.instanceGuid}.hb">${d.monitorLogDto.instanceName}</a>
                    </dis:column>
                    <dis:column title="日志时间" property="monitorLogDto.createTime"
                                class="${d.monitorLogDto.normal?'':'text-danger'}"/>
                    <dis:column title="<abbr title='连接用时(ms)'>连接用时(ms)</abbr>"
                                property="monitorLogDto.costTime"
                                class="${d.monitorLogDto.normal?'':'text-danger'}"/>
                    <dis:column title="<abbr title='响应数据大小(KB)'>响应数据大小(KB)</abbr>"
                                property="monitorLogDto.responseSizeAsKB"
                                class="${d.monitorLogDto.normal?'':'text-danger'}"/>
                    <dis:column title="备注" class="${d.monitorLogDto.normal?'':'text-danger'}">
                        <custom:substring_remark d="${d.monitorLogDto}"/>
                    </dis:column>
                </dis:table>
            </c:if>
        </div>
    </div>
</div>

<script>
    $(function () {
        new SearchResult();
    });
</script>
</body>
</html>

src/main/webapp/WEB-INF/jsp/user_profile.jsp
<%--
 * 
 * @author Shengzhao Li
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fun" uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<!DOCTYPE HTML>
<html>
<head>
    <title>用户设置</title>
</head>
<body>
<%--Alert--%>
<div class="row">
    <div class="col-md-12">
        <div class="alert alert-success" style="display: none;">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <div><em class="fui-check-circle"></em>
                <span id="updateProfileOK" style="display: none;">更新用户设置成功</span>
            </div>
        </div>
    </div>
</div>

<div>
    <div class="row">
        <div class="col-md-12">
            <h4>用户设置
                <small>修改密码</small>
            </h4>
            <form:form commandName="formDto" cssClass="form-horizontal">
                <div class="form-group">
                    <label class="col-sm-2 control-label">账号</label>

                    <div class="col-sm-8">
                        <p class="form-control-static">${SPRING_SECURITY_CONTEXT.authentication.principal.username}</p>
                    </div>
                </div>

                <div class="form-group">
                    <label for="oldPassword" class="col-sm-2 control-label">旧密码</label>

                    <div class="col-sm-8">
                        <form:password path="oldPassword" id="oldPassword" cssClass="form-control"
                                       placeholder="请输入旧密码" required="true" maxlength="255"/>
                        <p class="help-block">当前登录用户的密码</p>
                        <form:errors path="oldPassword" cssClass="text-danger"/>
                    </div>
                </div>

                <div class="form-group">
                    <label for="password" class="col-sm-2 control-label">新密码</label>

                    <div class="col-sm-8">
                        <form:password path="password" id="password" cssClass="form-control"
                                       placeholder="请输入新密码" required="true" maxlength="255"/>
                        <p class="help-block">新密码长度 >= 6</p>
                        <form:errors path="password" cssClass="text-danger"/>
                    </div>
                </div>

                <div class="form-group">
                    <label for="rePassword" class="col-sm-2 control-label">重复新密码</label>

                    <div class="col-sm-8">
                        <form:password path="rePassword" id="rePassword" cssClass="form-control"
                                       placeholder="请再次输入新密码" required="true" maxlength="255"/>
                        <p class="help-block">再次输入新密码</p>
                        <form:errors path="rePassword" cssClass="text-danger"/>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-primary"><em class="fui-check-circle"></em> 更新
                        </button>
                    </div>
                </div>
            </form:form>
        </div>
    </div>
</div>

<script>
    $(function () {
        new UserProfile('${param.alert}');
    });
</script>
</body>
</html>

src/main/webapp/WEB-INF/jsp/user_register.jsp
<%--
 * 
 * @author Shengzhao Li
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" trimDirectiveWhitespaces="true" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fun" uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<!DOCTYPE HTML>
<html>
<head>
    <title>用户注册</title>
</head>
<body>

<div>
    <div class="row">
        <div class="col-md-12">
            <h4>用户注册</h4>
            <form:form commandName="formDto" cssClass="form-horizontal">

                <div class="form-group">
                    <label for="username" class="col-sm-2 control-label">账号</label>

                    <div class="col-sm-8">
                        <form:input path="username" id="username" cssClass="form-control"
                                    placeholder="请输入账号" required="true" maxlength="40"/>
                        <p class="help-block">账号必须唯一</p>
                        <form:errors path="username" cssClass="text-danger"/>
                    </div>
                </div>

                <div class="form-group">
                    <label for="password" class="col-sm-2 control-label">密码</label>

                    <div class="col-sm-8">
                        <form:password path="password" id="password" cssClass="form-control"
                                       placeholder="请输入密码, 长度 >= 6" required="true" maxlength="255"/>
                        <p class="help-block">密码长度 >= 6</p>
                        <form:errors path="password" cssClass="text-danger"/>
                    </div>
                </div>
                <div class="form-group">
                    <label for="rePassword" class="col-sm-2 control-label">重复密码</label>

                    <div class="col-sm-8">
                        <form:password path="rePassword" id="rePassword" cssClass="form-control"
                                       placeholder="请再次输入密码" required="true" maxlength="255"/>
                        <p class="help-block">两次输入的密码要一致</p>
                        <form:errors path="rePassword" cssClass="text-danger"/>
                    </div>
                </div>

                <div class="form-group">
                    <label for="email" class="col-sm-2 control-label">邮箱</label>

                    <div class="col-sm-8">
                        <form:input path="email" id="email" cssClass="form-control"
                                    placeholder="请输入邮箱" maxlength="255" required="true"/>
                        <p class="help-block">邮箱是必填项</p>
                        <form:errors path="email" cssClass="text-danger"/>
                    </div>
                </div>
                <div class="form-group">
                    <label for="phone" class="col-sm-2 control-label">手机</label>

                    <div class="col-sm-8">
                        <form:input path="phone" id="phone" cssClass="form-control"
                                    placeholder="请输入手机号码" maxlength="255"/>
                        <p class="help-block">手机号码是可选的</p>
                        <form:errors path="phone" cssClass="text-danger"/>
                    </div>
                </div>

                <div class="form-group">
                    <label for="captcha" class="col-sm-2 control-label">验证码</label>

                    <div class="col-sm-8">
                        <div class="input-group">
                            <input type="text" name="${formDto.captchaKey}" class="form-control"
                                   placeholder="请输入右侧验证码" id="captcha" maxlength="10" required="required"/>
                            <span class="input-group-addon input-sm">
                                <img src="${contextPath}/captcha.hb" onclick="this.src = this.src+'?'" alt="Captcha"/>
                            </span>
                        </div>
                        <p class="help-block">验证码是必填项</p>
                    </div>
                </div>


                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-primary"><em class="fui-check-circle"></em> 注册
                        </button>
                        &nbsp;<a href="${contextPath}/login.hb" class="btn btn-sm btn-link">去登录</a>
                    </div>
                </div>
            </form:form>
        </div>
    </div>
</div>

</body>
</html>

src/main/webapp/WEB-INF/jsp/user_register_forbidden.jsp
<%--
 * 
 * @author Shengzhao Li
--%>

<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<!DOCTYPE HTML>
<html>
<head>
    <title>用户注册被禁止</title>
</head>
<body>

<div class="row">
    <div class="col-md-12">
        <div class="alert alert-danger">
            <div>
                <h4><em class="fui-info-circle"></em> OOps... </h4>
                当前系统设置为禁止用户注册

                <br/>
                <br/>

                <a href="javascript:history.back();">返回</a>
            </div>
        </div>
    </div>
</div>


</body>
</html>